depth=[0; 1;];
DATASET='MNIST';
ALPHA=0.5;
LR_LAMBDA=1;
Wd=load('MNIST Data/Simplified_MNIST_Dic.mat');
Wd=Wd.WDict;
data=load('MNIST Data/MNIST_Data.mat');
label=data.trls(1:5000);
test=data.tt_dat(:,1:1000);
test_lb=data.ttls(1:1000);
data=data.tr_dat(:,1:5000);
num_label=numel(unique(label));
S_cod=eye(size(Wd'*Wd))-Wd'*Wd;
for j=1:numel(depth)
  fprintf('Depth is %d\n',depth(j));
  NET_DEPTH=depth(j);
  network_lcod=load(sprintf('trained_network/MNIST_lcod_network_%f_%d.mat',ALPHA,NET_DEPTH+1));
  network_lcod=network_lcod.network;
  %network_lista=load(sprintf('trained_network/MNIST_lista_network_%f_%d.mat',ALPHA,NET_DEPTH));
  %network_lista=network_lista.network;
  fprintf('Calculating sparse code train data\n');
  fprintf('COD\n');
  features_cod_train=mass_lcod_fprop(data,Wd',S_cod,repmat(ALPHA,size(Wd,2),1),NET_DEPTH);
  fprintf('LCOD\n');
  features_lcod_train=mass_lcod_fprop(data,network_lcod.We,network_lcod.S,network_lcod.theta,NET_DEPTH);
  %fprintf('LISTA\n');
  %features_lista_train=mass_lista_fprop(data,network_lista.We,network_lista.S,network_lista.theta,NET_DEPTH);
  fprintf('Training\n');
  LRC_cod=LRClassifier(features_cod_train',label',num_label,LR_LAMBDA);
  LRC_lcod=LRClassifier(features_lcod_train',label',num_label,LR_LAMBDA);
  %LRC_lista=LRClassifier(features_lista_train',label',num_label,LR_LAMBDA);
  fprintf('Calculating sparse code test data\n');
  features_cod_test=mass_lcod_fprop(test,Wd',S_cod,repmat(ALPHA,size(Wd,2),1),NET_DEPTH);
  features_lcod_test=mass_lcod_fprop(test,network_lcod.We,network_lcod.S,network_lcod.theta,NET_DEPTH);
  %features_lista_test=mass_lista_fprop(data,network_lista.We,network_lista.S,network_lista.theta,NET_DEPTH);
  prediction_cod=LRpredict(LRC_cod,features_cod_test');
  prediction_lcod=LRpredict(LRC_lcod,features_lcod_test');
  %prediction_lista=LRpredict(LRC_lista,test');
  result.cod_err=(1-sum(prediction_cod(:)==test_lb(:))/numel(test_lb))*100;
  result.lcod_err=(1-sum(prediction_lcod(:)==test_lb(:))/numel(test_lb))*100;
  %result.lista_err=(1-(prediction_lista==test_lb')/numel(test_lb))*100;
  save(sprintf('logistic_regression/result/result_%d.mat',NET_DEPTH),'result');
end