iters=[0; 1; 5; 10];
DATASET='MNIST';
ALPHA=0.5;
LR_LAMBDA=1;
load(sprintf('trained_network/MNIST_lcod_network_%f_%d.mat',ALPHA,NET_DEPTH));
Wd=load('MNIST Data/Simplified_MNIST_Dic.mat');
Wd=Wd.WDict;
data=load('MNIST Data/MNIST_Data.mat');
label=trls;
test=data.tt_data;
test_lb=data.ttls;
data=data.tr_dat;
num_label=numel(unique(label));
S_cod=eye(size(Wd'*Wd))-Wd'*Wd;
for iter=iters
  fprintf('Depth is %d\n',iter);
  NET_DEPTH=iter;
  network_lcod=load(sprintf('trained_network/MNIST_lcod_network_%f_%d.mat',ALPHA,NET_DEPTH));
  network_lcod=network_lcod.network;
  network_lista=load(sprintf('trained_network/MNIST_lista_network_%f_%d.mat',ALPHA,NET_DEPTH));
  network_lista=network_lista.network;
  fprintf('Calculating sparse code train data\n');
  fprintf('COD\n');
  features_cod_train=mass_lcod_fprop(data,Wd',S_cod,ALPHA,NET_DEPTH);
  fprintf('LCOD\n');
  features_lcod_train=mass_lcod_fprop(data,network_lcod.We,network_lcod.S,network_lcod.theta,NET_DEPTH);
  fprintf('LISTA\n');
  features_lista_train=mass_lista_fprop(data,network_lista.We,network_lista.S,network_lista.theta,NET_DEPTH);
  fprintf('Training\n');
  LRC_cod=LRClassifier(features_cod_train',label',num_label,LR_LAMBDA);
  LRC_lcod=LRClassifier(features_lcod_train',label',num_label,LR_LAMBDA);
  LRC_lista=LRClassifier(features_lista_train',label',num_label,LR_LAMBDA);
  fprintf('Calculating sparse code test data\n');
  features_cod_test=mass_lcod_fprop(data,Wd',S_cod,ALPHA,NET_DEPTH);
  features_lcod_test=mass_lcod_fprop(data,network_lcod.We,network_lcod.S,network_lcod.theta,NET_DEPTH);
  features_lista_test=mass_lista_fprop(data,network_lista.We,network_lista.S,network_lista.theta,NET_DEPTH);
  prediction_cod=LRpredict(LRC_cod,test');
  prediction_lcod=LRpredict(LRC_lcod,test');
  prediction_lista=LRpredict(LRC_lista,test');
  result.cod_err=(1-(prediction_cod==test_lb')/numel(test_lb))*100;
  result.lcod_err=(1-(prediction_lcod==test_lb')/numel(test_lb))*100;
  result.lista_err=(1-(prediction_lista==test_lb')/numel(test_lb))*100;
  save(fprintf('logistic_regression/result/result_%d.mat',NET_DEPTH),'result');
end