datapath='USPS data/';
train_data=load([datapath 'USPS_Train_Data.mat']);
train_data=train_data.Train_Data;
COEFF_SIZE=size(train_data,1)*4;
ALPHA=0.001;
CONV_THRES=0.0001;
Wd=dict_learn(train_data, ALPHA, COEFF_SIZE, CONV_THRES);
dict.Wd=Wd;
dict.alpha=ALPHA;
dict.thres=CONV_THRES;
save(['my_sp_code/dict_',num2str(COEFF_SIZE,'%d'),'.mat'],'dict');
